kumuluzee:
  # name of our service
  name: test-service
  version: 1.0.2
  server:
    # url where our service will live
    base-url: http://localhost:5000
    http:
      port: 5000
      address: http://localhost
  env: 
    name: devF
  config:
    namespace: ''
    start-retry-delay-ms: 100
    max-retry-delay-ms: 500
    etcd:
      hosts: http://localhost:2379
    consul:
      hosts: http://localhost:8500
  discovery:
    ttl: 5000
    ping-interval: 2000
    consul:
      hosts: http://localhost:8500
    etcd:
      hosts: http://localhost:2379
settings:
  location: Oštrc
  house:
    owner:
      name: Alen
      age: 22
    sale: Y
    parts: "streha,vrata,okna,stene,pohištvo"
